version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: waterlily_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: waterlily
      POSTGRES_PASSWORD: waterlily
      POSTGRES_DB: waterlily_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - waterlily_network

networks:
  waterlily_network:
    driver: bridge

volumes:
  postgres_data:
